<?php

return [
    'system_monitoring_profile' => 'windows_local',
    'license_required' => true,
    'allow_unlicensed' => false,
    'log_minimal' => true,
    'profiles' => [
        'windows_local' => [
            'targethost' => 'http://system.localhost',
            'softwareid' => 'testproject',
            'currentversion' => '0',
            'update_mode' => 'partial',
            'auto_recovery' => true,
            'auto_download_update' => true,
            'auto_database_backup' => true,
            'update_target_root' => 'D:/wamp64/www/updater',
            'database_backup_root' => 'D:/wamp64/www/updater/system_monitoring_update_data/database_backups',
            'database_backup_times' => '00:00,12:00',
            'database_backup_retry_minutes' => 30,
        ],
        'live_server' => [
            'targethost' => 'https://your-live-domain.com',
            'softwareid' => 'your-software-slug',
            'currentversion' => '0',
            'update_mode' => 'partial',
            'auto_recovery' => true,
            'auto_download_update' => true,
            'auto_database_backup' => true,
            'update_target_root' => '/var/www/your-project',
            'database_backup_root' => '/var/www/your-project/system_monitoring_update_data/database_backups',
            'database_backup_times' => '00:00,12:00',
            'database_backup_retry_minutes' => 30,
        ],
        'ubuntu_server' => [
            'targethost' => 'https://your-live-domain.com',
            'softwareid' => 'your-software-slug',
            'currentversion' => '0',
            'update_mode' => 'partial',
            'auto_recovery' => true,
            'auto_download_update' => true,
            'auto_database_backup' => true,
            'update_target_root' => '/var/www/your-project',
            'database_backup_root' => '/var/www/your-project/system_monitoring_update_data/database_backups',
            'database_backup_times' => '00:00,12:00',
            'database_backup_retry_minutes' => 30,
        ],
    ],
];
